---
version: 1
update_configs:
- package_manager: "dotnet:nuget"
  directory: "/src/SimpleCachedApp"
  update_schedule: "daily"
- package_manager: "dotnet:nuget"
  directory: "/src/SimpleCachedPersistentStoreApp"
  update_schedule: "live"